import random

male_names = ["Jimmy", "Paul", "Merle", "Stacey", "Mitchell", "Lawrence", "Mark", "Don", "Christopher", "Lynn", "Mark",
              "William", "Blake", "Charles", "Moses", "Daniel", "Richard", "James", "Jose", "Jeffrey", "Sandy",
              "George", "Louis", "Nathaniel", "Nicholas", "Frank", "Marcus", "Stephen", "Clifford", "Gary", "Carlo",
              "Ronald", "Jose", "Jimmy", "Keith", "Leroy", "Frank", "Ronald", "Paul", "Alvin", "Miguel", "Patrick",
              "Greg", "Allen", "Gordon", "Jeremy", "Mark", "David", "Miguel", "Joseph", "Michael", "John", "Stephen",
              "Steven", "John", "Paul", "Mack", "Jessie", "Jose", "David", "George", "Carl", "Robert", "Robert", "John",
              "Gordon", "Thad", "Eduardo", "Brandon", "Brenton", "Salvatore", "David", "Robert", "James", "John",
              "Otto", "Roland", "Joe", "Daniel", "Ian", "Adrian", "Silas", "James", "Gary", "James", "Paul", "John",
              "Andrew", "Fred", "Wade", "Michael", "Harlan", "Clarence", "Norman", "Bruce", "Brandon", "Alfonso",
              "Michael", "Rick", "Adrian", "Rodrigo", "Donald", "Marcus", "Keith", "Randall", "Harry", "Clinton",
              "Ruben", "John", "William", "William", "Eric", "Joseph", "Paul", "Donald", "Mark", "David", "Julian",
              "John", "Don", "Michael", "John", "Matthew", "Heriberto", "Donald", "Robert", "David", "George",
              "Terence", "Ronald", "Daniel", "Steven", "Thomas", "Enrique", "Alfonso", "Stanley", "Lester", "Walter",
              "Robert", "Thomas", "Andrew", "Gary", "Norberto", "Richard", "Kyle", "Roger", "Adam", "Wayne", "Brian",
              "Jesse", "Christopher", "Michael", "Kirk", "Maurice", "Charles", "Eduardo", "Kevin", "John", "Emmitt",
              "Christopher", "Adam", "Charles", "Lyle", "Aaron", "Kevin", "Richard", "Paul", "Gary", "David", "Paul",
              "Ronald", "Jackie", "Andrew", "Joseph", "Elliot", "Darryl", "Peter", "Paul", "Ryan", "Ronald", "Nathan",
              "Lawrence", "Joseph", "Thomas", "Jamie", "Gilbert", "Arnold", "Gary", "Micheal", "John", "Dean",
              "Spencer", "Mark", "Kermit", "Jose", "Howard", "Neil", "Edward", "Kevin", "Theodore", "Thomas", "Zachary",
              "Alfred", "Howard", "Robert", "Dallas", "Harold", "Arthur", "Roosevelt", "Robert", "Harry", "Douglas",
              "Robert", "Kenneth", "Victor", "Dwight", "Joseph", "Derrick", "John", "Johnathan", "Matthew", "Daniel",
              "Edward", "Terrance", "Christopher", "Wayne", "Richard", "Jonathan", "George", "Samuel", "Robert",
              "Donald", "David", "Reginald", "Jeffrey", "Tony", "Gregory", "Robert", "Anthony", "Aaron", "Jack", "Eric",
              "Ronald", "Rocky", "Samuel", "Douglas", "Eric", "James", "Marc", "John", "Ryan", "Adrian", "Henry",
              "Patrick", "Barry", "Paul", "Harry", "Jeffrey", "Harry", "Martin", "George", "Edward", "Walter", "Bryan",
              "William", "Ronald", "John", "Bryant", "Trent", "Jesus", "Julio", "Wayne", "Theodore", "Kurt", "Stephen",
              "Robert", "Abraham", "Stephen", "Jack", "Jason", "Michael", "Mario", "Quentin", "James", "Roy", "Jerry",
              "Jerry", "David", "Clarence", "Donald", "Israel", "Bruce", "Chris", "Bobby", "Sidney", "Luis", "Douglas",
              "Derek", "James", "Eric", "Thomas", "Justin", "Roberto", "Kevin", "Eric", "Jose", "Douglas", "Matthew",
              "Leonard", "Joseph", "Patrick", "Phillip", "Brian", "Gail", "Rick", "Michael", "Brett", "Bruce", "Casey",
              "Henry", "Steve", "Kenneth", "Ronald", "Lawrence", "Paul", "Dylan", "Carl", "Martin", "Alfred", "Matthew",
              "Brandon", "Glenn", "Rick", "Dylan", "Thomas", "Theodore", "Donald", "Marc", "Phillip", "Michael", "John",
              "Larry", "William", "Mario", "Paul", "Samuel", "John", "David", "Eric", "Thomas", "William", "George",
              "John", "Lowell", "Ronald", "Arthur", "James", "Charlie", "Dan", "Carlos", "Steven", "Daniel", "Loren",
              "Bobbie", "Thanh", "Gerald", "Brandon", "James", "Danny", "Miles", "Jeffery", "Robert", "Jimmy", "Philip",
              "Cedric", "Mark", "Ali", "Leon", "Vaughn", "Rafael", "Gerardo", "Jose", "Ira", "Wayne", "Edward", "John",
              "Sam", "Vernon", "William", "Robin", "William", "John", "Michael", "Conrad", "John", "Robert", "Robert",
              "Richard", "Paul", "John", "Steven", "Kyle", "Richard", "Israel", "Juan", "Melvin", "James", "George",
              "Alex", "Michael", "Clinton", "Angel", "Ned", "Mario", "William", "Eric", "Rodney", "Joe", "Philip",
              "Leon", "Brian", "Larry", "William", "Joseph", "Kenneth", "Evan", "Charles", "John", "Gregory", "Nolan",
              "Vincent", "Richard", "John", "Glenn", "Richard", "Ulysses", "Jerry", "Robert", "Darrel", "Adolph",
              "Boyd", "Wilbur", "Ernie", "Robert", "Edward", "Charles", "Lee", "Dale", "Douglas", "Donald", "Allan",
              "Francisco", "Edward", "Paul", "David", "Jeffrey", "Barry", "Ross", "Christopher", "Kenneth", "Dennis",
              "Julian", "Ken", "James", "Ramon", "Freddy", "James", "David", "Stephen", "Jason", "Ronald", "Kenneth",
              "Kenneth", "Justin", "John", "Edward", "Stuart", "Anthony", "Billy", "Barry", "Chad", "Bruce", "Leonard",
              "David", "Bennie", "Travis", "Robert", "Timothy", "Edward", "Winford", "Robert", "Avery", "Nicholas",
              "Virgil", "Timothy", "Rudy", "Raymond", "Matthew", "Elmer", "Brian"]
female_names = ["Janet", "Deborah", "Judith", "Doris", "Marjorie", "Tiffany", "Amanda", "Robin", "Jennifer", "Deborah",
                "Gloria", "Donna", "Lillian", "Joyce", "Olga", "Virginia", "Catarina", "Jamie", "Bernice", "Roberta",
                "Gwendolyn", "Mary", "Jason", "Amber", "Ann", "Alene", "Dana", "Dorothy", "Joyce", "Vanessa", "Mai",
                "Beverly", "Carolyn", "Maria", "Ann", "Marilyn", "Gina", "Briana", "Bridgette", "Karen", "Jennifer",
                "Joanne", "Lori", "Jennifer", "Oralia", "Joann", "Maria", "Odilia", "Carol", "Theresa", "Mary",
                "Meredith", "Marsha", "Janice", "Dena", "Pauline", "Florence", "Debbie", "Rosalie", "Kathleen",
                "Mercedes", "Carolyn", "Lory", "Stella", "Juana", "Karen", "Jenny", "Geraldine", "Sherry", "Doris",
                "Rena", "Dora", "Anabel", "Deborah", "Helen", "Dana", "Albertine", "Bonnie", "Cheryl", "Janet",
                "Janice", "Erin", "Nora", "Alison", "Claretta", "Victoria", "Amber", "Evelyn", "Betty", "Velma",
                "Kayla", "Kathleen", "Barbara", "Bettie", "Helen", "Joyce", "Michelle", "Loretta", "Dolly", "Minnie",
                "Bernice", "Delsie", "Reina", "Maria", "Katherine", "Loretta", "Cheryl", "Tamra", "Margaret", "Cherie",
                "Andrea", "Barbara", "Amelia", "Tracy", "Ella", "Veronica", "Holly", "Lanette", "Maureen", "Tammy",
                "Penelope", "Bertha", "Wanda", "Lisa", "Cindy", "Kelly", "Anita", "Wilma", "Leann", "Sheila", "Helen",
                "Valencia", "Elinor", "Matilde", "Maria", "Pearl", "Michele", "Dorothy", "Valarie", "Sarah", "Delores",
                "Sara", "Mona", "Sarah", "Sue", "Adrian", "Norma", "Terry", "Tonja", "Tracy", "Bernice", "Virginia",
                "Judith", "Leigh", "Sheena", "Nohemi", "Lisa", "Virginia", "Helen", "Brandy", "Carrie", "Kathryn",
                "Cheryl", "Chelsey", "Kelly", "Erin", "Eve", "Brenda", "Patricia", "Isabel", "Diana", "Mindy", "Tammie",
                "Ruth", "Sylvia", "Christine", "Elena", "Shirley", "Doris", "Catherine", "Toni", "Debra", "Jane",
                "Keli", "Evelyn", "Robert", "Amy", "Polly", "Luella", "Betsy", "Mary", "Cherie", "Renee", "Ann",
                "Katherin", "Carmen", "Angela", "Rita", "Flossie", "Lina", "Sue", "Teri", "Cheryl", "Candice", "Anita",
                "Mary", "Ruth", "Connie", "Dorothy", "Wendy", "Elizabeth", "Teresa", "Jamie", "Isabel", "Maria",
                "Susan", "Kathleen", "Mary", "Nancy", "Shanta", "Barbara", "Blanche", "Marlene", "Bonnie", "Phyllis",
                "Brenda", "Talia", "Virginia", "Louanne", "Jacqueline", "Donna", "Stephen", "Jessica", "Carla",
                "Louise", "Cora", "Carolyn", "Elsie", "Alesia", "Rosie", "Karen", "Tasha", "Gladys", "Kathleen",
                "Melba", "Rita", "Mary", "Janice", "Anne", "Yvonne", "Melanie", "Kerry", "Mary", "Angelica", "Colleen",
                "Maria", "Amber", "Maria", "Nadine", "Tiara", "Julie", "Celeste", "Angela", "Nicole", "Aileen",
                "Nicole", "Mary", "Yulanda", "Debra", "Margaret", "Kathleen", "Beulah", "Pauline", "Jean", "Beverly",
                "Judith", "Carol", "Nancy", "Connie", "Bonita", "Sandra", "Martha", "Lindsay", "Julie", "Tara", "Tammy",
                "Marilynn", "Marian", "Polly", "Dana", "Olivia", "Elsie", "Keshia", "Julia", "Ethel", "Patricia",
                "Frieda", "Jennifer", "Barbara", "Kathy", "Edna", "Dovie", "Diane", "Sondra", "Pamela", "Molly",
                "Maria", "Terry", "Christy", "Jeannette", "Dawn", "Maxine", "Margret", "Clarice", "Lillian", "Lizabeth",
                "Michelle", "Alicia", "Jennifer", "Lorraine", "Dorothy", "Theresa", "Shannon", "Maribel", "Rebecca",
                "Evelyn", "Katie", "Lisa", "Sandra", "Angela", "Diana", "Brenda", "Beth", "Kellie", "Jacqueline",
                "Evelyn", "Barbara", "Christina", "Natalie", "Charlotte", "Stephanie", "Sally", "Nancy", "Lisa",
                "Charity", "Maggie", "Tracy", "Freda", "Chelsea", "Mercedes", "Carolyn", "Sofia", "Sandra", "Catherine",
                "Anna", "Doris", "Barbara", "Michele", "Michelle", "April", "Dorothy", "Penelope", "Wanda", "Pamela",
                "Diane", "Jeannie", "Bobbie", "Renee", "Andrea", "April", "Judith", "Genevieve", "Katharine", "Mary",
                "Carol", "Jill", "Linda", "Modesta", "Kristina", "Tonya", "Erin", "Evelyn", "Maria", "Barbara",
                "Rebecca", "Shannon", "Susan", "Karissa", "Barbra", "Irmgard", "Connie", "Norma", "Mary", "Lilly",
                "Sharon", "Ruth", "Shayla", "Theresa", "Sherri", "Rhonda", "Mary", "Eleanor", "Kristen", "Tessie",
                "Maria", "Jean", "Kelly", "Betty", "Mary", "Geraldine", "Phyllis", "Mary", "Bobbie", "Kassie",
                "Cynthia", "Genevieve", "Mary", "Esther", "Rebecca", "Deborah", "Karen", "Haley", "Donna", "Theresa",
                "Edith", "Sharon", "Rebecca", "Maria", "Margery", "Hattie", "Melissa", "Tabitha", "Connie", "Marjorie",
                "Jessie", "Jennifer", "Patricia", "Chandra", "Doris", "Cynthia", "Barbara", "Judy", "Rita", "Kendra",
                "Loretta", "Dina", "Maria", "Caryn", "Carmen", "Katherine", "Marjorie", "Mary", "Evelyn", "Ruth",
                "Robin", "Rivka", "Emily", "Ruby", "Ada", "Mabel", "Lisa", "Inez", "Hannah", "Joanne", "Nancy", "Diane",
                "Dominque", "Sarah", "Ruthanne", "Laura", "Beverly", "Eva", "Margarita", "Emily", "Jennifer", "Beverly",
                "Judith", "Gwen", "Lori", "Amanda", "Margaret", "Anna", "Rachel", "Kristen", "Sherrie", "Lisa",
                "Amanda", "Karen", "Dolly", "Christy", "Diane", "Fabiola", "Mary", "Jessica", "Julie", "Karen", "Debra",
                "Shanelle", "Roseline", "Arlene"]
last_names = ["Okon", "Bartley", "Tavolario", "Townsend", "Mckeon", "Johnson", "Runge", "Chevere", "Finley", "Bishop",
              "Harton", "Pierce", "Williamson", "Walker", "Foster", "Neumeister", "Lewis", "Doss", "Noonan", "Hurst",
              "Johnson", "Kelling", "Ellis", "Smith", "Cattaneo", "Newell", "Morgan", "Castillo", "Elrod", "Swedenburg",
              "Levin", "Edelstein", "Allen", "Campbell", "Harriman", "Haynes", "Quimby", "Berndt", "Tewani", "Raiola",
              "Benjamin", "Child", "Hawn", "Thornburg", "King", "Fountain", "Jones", "Mcdonald", "Jones", "Turner",
              "Benedict", "Callen", "Erekson", "Dennis", "Barrera", "Chapman", "Rojo", "Murphy", "Mccoy", "Brown",
              "Huang", "Vidot", "Dronick", "Mosley", "Thompson", "Tirk", "Hearn", "Pratt", "Hayes", "Dunneback",
              "Stokes", "Bowers", "Jones", "Leef", "Hart", "Miller", "Aubrey", "Madigan", "Johnson", "Finch", "Halley",
              "Phillips", "Thurn", "Bellanger", "Salazar", "Anderson", "Keirnan", "Mendes", "Mckinney", "Fulvio",
              "Mccarthy", "Mitchell", "Brown", "Green", "Williams", "Palomares", "Pool", "Campbell", "Morris",
              "Mccormick", "Hughes", "Woods", "Bertolini", "Christner", "Hale", "Rice", "Emmi", "Peek", "Evans",
              "Jones", "Horst", "Thornton", "Dykstra", "Crossman", "Lazewski", "Leidall", "Piraino", "Coulter",
              "Cooley", "Mathews", "Eld", "Christensen", "Smith", "Garza", "Petterson", "Mcclendon", "Austin", "Powell",
              "Principe", "Mathews", "Price", "Davis", "Tice", "Roser", "Polk", "Diaz", "Immediato", "Ransom", "Hill",
              "Miller", "Londono", "Edge", "Rodriguez", "Saulsberry", "Hinnenkamp", "Adams", "Proctor", "Copeland",
              "Holder", "Roose", "Carter", "Formella", "Glaser", "Klingenberg", "Pearce", "Johnson", "Maddox",
              "Hileman", "Waring", "Mcgaha", "Jones", "Beasley", "Kasper", "Goodrich", "Merchant", "Woodcock", "Rowe",
              "Copley", "Bowie", "King", "Gray", "Gutierrez", "Hearns", "Hall", "Minnis", "Talley", "Foulkes",
              "Hoagland", "Ortega", "Lesperance", "Gilbert", "Hoy", "Vierk", "Martin", "Anaya", "Hall", "Byrd", "Diaz",
              "Davidson", "Mclaughlin", "Noto", "Kays", "Billingsley", "Hayes", "Johnson", "Mahnken", "Banton",
              "Anglin", "Hatfield", "Whitman", "Daniels", "Duhon", "Wilson", "Wolf", "Kern", "Noah", "Cookson",
              "Carnahan", "Luskey", "Figueroa", "Ferrara", "Ohno", "Collins", "Holliday", "Mullins", "Watley",
              "Salamanca", "Duey", "Miller", "Mccray", "Clevenger", "Gallogly", "Kosky", "Lee", "Driscoll", "Miller",
              "Butler", "Yates", "Deleon", "Blanche", "Stokes", "Fox", "Potter", "Los", "Mcdevitt", "Mason", "Gonzalez",
              "Porter", "Eberhart", "Mcdonald", "Porter", "Pocius", "Phillips", "Bernier", "Rollins", "Bruch", "Ladner",
              "Jones", "Stutts", "Lala", "Menchaca", "Goodrich", "Wallick", "Williams", "Ramirez", "Coyne", "Folts",
              "Wright", "Normand", "Perkins", "Gaunt", "Mallin", "Keller", "Nokes", "Guttmann", "Scarnati", "Still",
              "Andrews", "Anderson", "Laverty", "Rodriguez", "Brown", "Langley", "Schaffner", "Flakes", "Jenkins",
              "Hoffman", "Dreesman", "Smith", "Flint", "Fewell", "Price", "Martin", "Manley", "Ansley", "Seidel",
              "Jandres", "Evans", "Schepker", "Key", "Cox", "Troia", "Cogswell", "Jarrard", "Sapienza", "Cuellar",
              "Santos", "Gutierrez", "Strohmayer", "Weston", "Livingstone", "Kaiser", "Gates", "Richardson",
              "Gutierrez", "Montes", "Keenan", "Brown", "Blackburn", "Cull", "Cheek", "Bebee", "Bond", "Thompson",
              "Bass", "Rodriguez", "Lofaro", "Thomas", "Rexford", "Kissinger", "Rush", "Schuetz", "Phillips", "Graham",
              "Seefeldt", "Clinard", "Smith", "Brown", "Carbajal", "Booth", "Hupp", "Allison", "Acree", "Eldridge",
              "Tracey", "Owens", "Kao", "Scheid", "Freudenstein", "Havener", "Boyd", "Baumgartner", "Simas", "Troutt",
              "Goodwin", "Stafford", "Blackwell", "Kirby", "Flanagan", "Wheeler", "Schoonmaker", "Taylor", "Bailey",
              "Sanchez", "Godsey", "Grimmer", "Stone", "Edwards", "Kimmel", "Jones", "Robinson", "Edwards", "Buchner",
              "Whitaker", "Pfeiffer", "Tobar", "Schroder", "Lautman", "Wilkinson", "Taylor", "Minjares", "Cerny",
              "Lopez", "Cambron", "Williams", "Hill", "Pettiford", "Zambrana", "Travis", "Lee", "Porter", "Sherman",
              "Sanders", "Knight", "Stewart", "Bentley", "Cox", "Smith", "Bermudez", "Riina", "Taylor", "Wallace",
              "Sekel", "Pearson", "Ford", "Thrasher", "Henderson", "Morgan", "Estrella", "Speth", "Westerheide",
              "Hernandez", "Moon", "Crutchfield", "Parmer", "Melson", "Reitmeier", "Batchelor", "Washington", "Lee",
              "Poulin", "Fowler", "Zeigler", "Mitchell", "Chen", "Waters", "Blevins", "Freeman", "Ruiz", "Graves",
              "Bowers", "Rumsey", "Hurtado", "Slocum", "Johnson", "Snyder", "Wood", "Hawkins", "Harmon", "Buck",
              "Simpson", "Williams", "Edwards", "Riddick", "Douglas", "Epstein", "Bowen", "Sherrard", "Tran", "Smith",
              "Silva", "Colby", "Clarkson", "Davis", "Snoddy", "Lee", "Mabe", "Ruiz", "Gamez", "Lamoreaux", "Anglin",
              "Washington", "Marty", "Hearnsberger", "Williams", "Sutterfield", "Wentz", "Murff", "Warney", "Thoennes",
              "Knight", "Hill", "Bouchard", "Hall", "Darling", "Sisto", "Harris", "Walsh", "Wolfenbarger", "Harr",
              "Anding", "Staebell", "Marcinkowski", "Swavely", "Benton", "Hussey", "Dixon", "Pappas", "Jules", "Lawson",
              "Sylvester", "Pelletier", "Lang", "Dykas", "Stokes", "Monsen", "Shoe", "Morrison", "Kinsler", "Pascoe",
              "Martinez", "Hatfield", "Earley", "Tudor", "Hand", "Sphon", "Kasprowicz", "Harris", "Mccoy", "Stolte"]


def get_name(filename):
    if filename == "male":
        return random.choice(male_names)
    if filename == "female":
        return random.choice(female_names)
    if filename == "last":
        return random.choice(last_names)
    return ""


def get_first_name(gender=None):
    if gender not in ('male', 'female'):
        gender = random.choice(('male', 'female'))
    return get_name(gender).capitalize()


def get_last_name():
    return get_name('last').capitalize()


def get_full_name(gender=None):
    return "{0} {1}".format(get_first_name(gender), get_last_name())
